name: Selenium WebDriver CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Chrome
      run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
    - name: Build
      run: dotnet build
    - name: Run TestProject1 tests
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject1 tests"
        dotnet test TestProject1/TestProject1.csproj --verbosity quiet
   
